/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PageHome {
    }
    interface PageProjects {
    }
}
declare global {
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageProjectsElement extends Components.PageProjects, HTMLStencilElement {
    }
    var HTMLPageProjectsElement: {
        prototype: HTMLPageProjectsElement;
        new (): HTMLPageProjectsElement;
    };
    interface HTMLElementTagNameMap {
        "page-home": HTMLPageHomeElement;
        "page-projects": HTMLPageProjectsElement;
    }
}
declare namespace LocalJSX {
    interface PageHome {
    }
    interface PageProjects {
    }
    interface IntrinsicElements {
        "page-home": PageHome;
        "page-projects": PageProjects;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-projects": LocalJSX.PageProjects & JSXBase.HTMLAttributes<HTMLPageProjectsElement>;
        }
    }
}
