/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MadnessbarRouter {
    }
}
declare global {
    interface HTMLMadnessbarRouterElement extends Components.MadnessbarRouter, HTMLStencilElement {
    }
    var HTMLMadnessbarRouterElement: {
        prototype: HTMLMadnessbarRouterElement;
        new (): HTMLMadnessbarRouterElement;
    };
    interface HTMLElementTagNameMap {
        "madnessbar-router": HTMLMadnessbarRouterElement;
    }
}
declare namespace LocalJSX {
    interface MadnessbarRouter {
    }
    interface IntrinsicElements {
        "madnessbar-router": MadnessbarRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "madnessbar-router": LocalJSX.MadnessbarRouter & JSXBase.HTMLAttributes<HTMLMadnessbarRouterElement>;
        }
    }
}
